### PR TITLE
Remove the global callback

### PR DESCRIPTION
**Pull request by jrouzierinverse**
Remove the need of a global callback this will allow the code to be more threadsafe

### CODE REVIEW

**Comment by jrouzierinverse** [comment]
Bump

**Comment by twilde** [comment]
Sorry we didn't notice this! Can you please split out the whitespace fixes into a separate commit so they can be reviewed separately?

**Comment by jrouzierinverse** [comment]
No problem.

**Comment by jrouzierinverse** [comment]
Done I just included the commit without the whitespace cleanup

**Comment by jrouzierinverse** [comment]
Is there anything else needed for this?

**Comment by maddingue** [comment]
Clever use of the user data. Given the current backlog, this is worth of a release.

**Comment by maddingue** [comment]
Part of release 0.18

**Pull request merged**
